version: '3.8'

services:
  nana-caring-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - nana-caring-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - nana-caring-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./uploads:/var/www/uploads
    depends_on:
      - nana-caring-backend
    restart: unless-stopped
    networks:
      - nana-caring-network

volumes:
  redis_data:

networks:
  nana-caring-network:
    driver: bridge
