const { Product } = require('../models');

const sampleProducts = [
  // Healthcare Products (10)
  {
    name: 'Pregnavit M 30 Capsules',
    brand: 'Clicks',
    description: 'Essential vitamins for pregnancy',
    detailedDescription: 'Pregnavit M 30 Capsules are formulated for women before, during and after pregnancy.',
    price: 285.99,
    category: 'Healthcare',
    subcategory: 'Pregnancy Vitamins',
    sku: 'HLT001',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
    images: [],
    inStock: true,
    stockQuantity: 50,
    ingredients: 'Folic Acid, Iron, Calcium',
    weight: '30 capsules',
    manufacturer: 'Clicks',
    tags: ['pregnancy', 'vitamins'],
    rating: 4.5,
    reviewCount: 23
  },
  {
    name: 'Panadol Extra 24 Tablets',
    brand: 'GSK',
    description: 'Pain relief tablets',
    detailedDescription: 'Effective relief from headaches and pain',
    price: 68.99,
    category: 'Healthcare',
    subcategory: 'Pain Relief',
    sku: 'HLT002',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    images: [],
    inStock: true,
    stockQuantity: 80,
    ingredients: 'Paracetamol 500mg',
    weight: '24 tablets',
    manufacturer: 'GSK',
    tags: ['pain relief', 'headache'],
    rating: 4.4,
    reviewCount: 67
  },
  {
    name: 'Vitamin C 1000mg Tablets',
    brand: 'Dis-Chem',
    description: 'Immune system support',
    detailedDescription: 'High strength vitamin C for immune health',
    price: 129.99,
    category: 'Healthcare',
    subcategory: 'Vitamins',
    sku: 'HLT003',
    image: 'https://images.unsplash.com/photo-1550572017-4272555a73e8?w=400',
    images: [],
    inStock: true,
    stockQuantity: 60,
    ingredients: 'Vitamin C 1000mg',
    weight: '60 tablets',
    manufacturer: 'Dis-Chem',
    tags: ['vitamins', 'immune'],
    rating: 4.6,
    reviewCount: 45
  },
  {
    name: 'Antiseptic Liquid 500ml',
    brand: 'Dettol',
    description: 'Antiseptic disinfectant',
    detailedDescription: 'Kills 99.9% of germs',
    price: 55.00,
    category: 'Healthcare',
    subcategory: 'First Aid',
    sku: 'HLT004',
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
    images: [],
    inStock: true,
    stockQuantity: 40,
    weight: '500ml',
    manufacturer: 'Dettol',
    tags: ['antiseptic', 'disinfectant'],
    rating: 4.7,
    reviewCount: 32
  },
  {
    name: 'Digital Thermometer',
    brand: 'Omron',
    description: 'Fast digital thermometer',
    detailedDescription: 'Accurate temperature reading in 60 seconds',
    price: 85.00,
    category: 'Healthcare',
    subcategory: 'Medical Devices',
    sku: 'HLT005',
    image: 'https://images.unsplash.com/photo-1584555613497-9ecf9dd06f68?w=400',
    images: [],
    inStock: true,
    stockQuantity: 30,
    weight: '50g',
    manufacturer: 'Omron',
    tags: ['thermometer', 'medical'],
    rating: 4.3,
    reviewCount: 18
  },
  {
    name: 'Hand Sanitizer 500ml',
    brand: 'Clicks',
    description: 'Antibacterial hand sanitizer',
    detailedDescription: '70% alcohol-based hand sanitizer',
    price: 45.00,
    category: 'Healthcare',
    subcategory: 'Hygiene',
    sku: 'HLT006',
    image: 'https://images.unsplash.com/photo-1584744982731-e1c3048464bc?w=400',
    images: [],
    inStock: true,
    stockQuantity: 100,
    weight: '500ml',
    manufacturer: 'Clicks',
    tags: ['sanitizer', 'hygiene'],
    rating: 4.5,
    reviewCount: 55
  },
  {
    name: 'Cough Syrup 200ml',
    brand: 'Benylin',
    description: 'Relief from coughs',
    detailedDescription: 'Non-drowsy cough syrup',
    price: 72.50,
    category: 'Healthcare',
    subcategory: 'Cold & Flu',
    sku: 'HLT007',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
    images: [],
    inStock: true,
    stockQuantity: 45,
    weight: '200ml',
    manufacturer: 'Benylin',
    tags: ['cough', 'cold'],
    rating: 4.2,
    reviewCount: 28
  },
  {
    name: 'Blood Pressure Monitor',
    brand: 'Omron',
    description: 'Automatic BP monitor',
    detailedDescription: 'Digital blood pressure monitor',
    price: 650.00,
    category: 'Healthcare',
    subcategory: 'Medical Devices',
    sku: 'HLT008',
    image: 'https://images.unsplash.com/photo-1615486511484-92e172cc4fe0?w=400',
    images: [],
    inStock: true,
    stockQuantity: 15,
    weight: '300g',
    manufacturer: 'Omron',
    tags: ['blood pressure', 'monitor'],
    rating: 4.8,
    reviewCount: 42
  },
  {
    name: 'Multivitamin Tablets 60s',
    brand: 'Centrum',
    description: 'Complete multivitamin',
    detailedDescription: 'All essential vitamins and minerals',
    price: 189.99,
    category: 'Healthcare',
    subcategory: 'Vitamins',
    sku: 'HLT009',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400',
    images: [],
    inStock: true,
    stockQuantity: 70,
    weight: '60 tablets',
    manufacturer: 'Centrum',
    tags: ['multivitamin', 'health'],
    rating: 4.6,
    reviewCount: 88
  },
  {
    name: 'First Aid Kit',
    brand: 'Dis-Chem',
    description: 'Complete first aid kit',
    detailedDescription: 'Essential first aid supplies',
    price: 250.00,
    category: 'Healthcare',
    subcategory: 'First Aid',
    sku: 'HLT010',
    image: 'https://images.unsplash.com/photo-1603398938378-e54eab446dde?w=400',
    images: [],
    inStock: true,
    stockQuantity: 25,
    weight: '500g',
    manufacturer: 'Dis-Chem',
    tags: ['first aid', 'emergency'],
    rating: 4.7,
    reviewCount: 36
  },

  // Education Products (10)
  {
    name: 'Mathematics Textbook Grade 10',
    brand: 'Oxford',
    description: 'Grade 10 maths textbook',
    detailedDescription: 'Complete curriculum coverage',
    price: 450.00,
    category: 'Education',
    subcategory: 'Textbooks',
    sku: 'EDU001',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=400',
    images: [],
    inStock: true,
    stockQuantity: 25,
    weight: '500g',
    manufacturer: 'Oxford',
    tags: ['mathematics', 'textbook'],
    rating: 4.2,
    reviewCount: 15
  },
  {
    name: 'Scientific Calculator',
    brand: 'Casio',
    description: 'Advanced calculator',
    detailedDescription: '240 functions',
    price: 180.00,
    category: 'Education',
    subcategory: 'Calculators',
    sku: 'EDU002',
    image: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400',
    images: [],
    inStock: true,
    stockQuantity: 40,
    weight: '150g',
    manufacturer: 'Casio',
    tags: ['calculator', 'mathematics'],
    rating: 4.8,
    reviewCount: 28
  },
  {
    name: 'English Dictionary',
    brand: 'Oxford',
    description: 'Comprehensive English dictionary',
    detailedDescription: 'Over 100,000 definitions',
    price: 320.00,
    category: 'Education',
    subcategory: 'Reference Books',
    sku: 'EDU003',
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400',
    images: [],
    inStock: true,
    stockQuantity: 30,
    weight: '800g',
    manufacturer: 'Oxford',
    tags: ['dictionary', 'english'],
    rating: 4.5,
    reviewCount: 22
  },
  {
    name: 'Art Set 24 Pieces',
    brand: 'Faber-Castell',
    description: 'Complete art supplies',
    detailedDescription: 'Pencils, crayons, and markers',
    price: 125.00,
    category: 'Education',
    subcategory: 'Art Supplies',
    sku: 'EDU004',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=400',
    images: [],
    inStock: true,
    stockQuantity: 50,
    weight: '300g',
    manufacturer: 'Faber-Castell',
    tags: ['art', 'drawing'],
    rating: 4.6,
    reviewCount: 35
  },
  {
    name: 'School Backpack',
    brand: 'Adidas',
    description: 'Durable school backpack',
    detailedDescription: 'Multiple compartments, ergonomic',
    price: 450.00,
    category: 'Education',
    subcategory: 'School Bags',
    sku: 'EDU005',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400',
    images: [],
    inStock: true,
    stockQuantity: 20,
    weight: '600g',
    manufacturer: 'Adidas',
    tags: ['backpack', 'school'],
    rating: 4.7,
    reviewCount: 48
  },
  {
    name: 'Notebook Pack (5)',
    brand: 'Croxley',
    description: 'A4 ruled notebooks',
    detailedDescription: 'Pack of 5 quality notebooks',
    price: 85.00,
    category: 'Education',
    subcategory: 'Stationery',
    sku: 'EDU006',
    image: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=400',
    images: [],
    inStock: true,
    stockQuantity: 100,
    weight: '400g',
    manufacturer: 'Croxley',
    tags: ['notebooks', 'stationery'],
    rating: 4.3,
    reviewCount: 62
  },
  {
    name: 'Geometry Set',
    brand: 'Staedtler',
    description: 'Complete geometry tools',
    detailedDescription: 'Compass, protractor, ruler, set squares',
    price: 95.00,
    category: 'Education',
    subcategory: 'Stationery',
    sku: 'EDU007',
    image: 'https://images.unsplash.com/photo-1596495577886-d920f1fb7238?w=400',
    images: [],
    inStock: true,
    stockQuantity: 45,
    weight: '200g',
    manufacturer: 'Staedtler',
    tags: ['geometry', 'mathematics'],
    rating: 4.4,
    reviewCount: 27
  },
  {
    name: 'Science Textbook Grade 11',
    brand: 'Cambridge',
    description: 'Grade 11 science textbook',
    detailedDescription: 'Physics, chemistry, and biology',
    price: 520.00,
    category: 'Education',
    subcategory: 'Textbooks',
    sku: 'EDU008',
    image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400',
    images: [],
    inStock: true,
    stockQuantity: 18,
    weight: '650g',
    manufacturer: 'Cambridge',
    tags: ['science', 'textbook'],
    rating: 4.5,
    reviewCount: 14
  },
  {
    name: 'Pen Pack (10)',
    brand: 'Bic',
    description: 'Blue ballpoint pens',
    detailedDescription: 'Pack of 10 quality pens',
    price: 35.00,
    category: 'Education',
    subcategory: 'Stationery',
    sku: 'EDU009',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=400',
    images: [],
    inStock: true,
    stockQuantity: 150,
    weight: '100g',
    manufacturer: 'Bic',
    tags: ['pens', 'stationery'],
    rating: 4.2,
    reviewCount: 75
  },
  {
    name: 'Educational World Map',
    brand: 'MapStudio',
    description: 'Large educational wall map',
    detailedDescription: 'Detailed world map for learning',
    price: 145.00,
    category: 'Education',
    subcategory: 'Educational Materials',
    sku: 'EDU010',
    image: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=400',
    images: [],
    inStock: true,
    stockQuantity: 35,
    weight: '150g',
    manufacturer: 'MapStudio',
    tags: ['map', 'geography'],
    rating: 4.6,
    reviewCount: 19
  },

  // Groceries Products (10)
  {
    name: 'Fresh Whole Milk 2L',
    brand: 'Clover',
    description: 'Fresh full cream milk',
    detailedDescription: 'Premium quality milk',
    price: 32.99,
    category: 'Groceries',
    subcategory: 'Dairy',
    sku: 'GRO001',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    images: [],
    inStock: true,
    stockQuantity: 100,
    weight: '2L',
    manufacturer: 'Clover',
    tags: ['milk', 'dairy'],
    rating: 4.7,
    reviewCount: 45
  },
  {
    name: 'Brown Bread 700g',
    brand: 'Albany',
    description: 'Whole wheat bread',
    detailedDescription: 'Healthy brown bread',
    price: 18.99,
    category: 'Groceries',
    subcategory: 'Bakery',
    sku: 'GRO002',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    images: [],
    inStock: true,
    stockQuantity: 80,
    weight: '700g',
    manufacturer: 'Albany',
    tags: ['bread', 'bakery'],
    rating: 4.4,
    reviewCount: 52
  },
  {
    name: 'Fresh Eggs 18s',
    brand: 'Nulaid',
    description: 'Large fresh eggs',
    detailedDescription: 'Free range eggs',
    price: 58.99,
    category: 'Groceries',
    subcategory: 'Dairy',
    sku: 'GRO003',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
    images: [],
    inStock: true,
    stockQuantity: 65,
    weight: '18 eggs',
    manufacturer: 'Nulaid',
    tags: ['eggs', 'fresh'],
    rating: 4.6,
    reviewCount: 38
  },
  {
    name: 'Rice 2kg',
    brand: 'Tastic',
    description: 'Long grain white rice',
    detailedDescription: 'Premium quality rice',
    price: 42.99,
    category: 'Groceries',
    subcategory: 'Grains',
    sku: 'GRO004',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
    images: [],
    inStock: true,
    stockQuantity: 90,
    weight: '2kg',
    manufacturer: 'Tastic',
    tags: ['rice', 'grains'],
    rating: 4.5,
    reviewCount: 67
  },
  {
    name: 'Cooking Oil 2L',
    brand: 'Sunfoil',
    description: 'Sunflower cooking oil',
    detailedDescription: 'Pure sunflower oil',
    price: 54.99,
    category: 'Groceries',
    subcategory: 'Cooking',
    sku: 'GRO005',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    images: [],
    inStock: true,
    stockQuantity: 70,
    weight: '2L',
    manufacturer: 'Sunfoil',
    tags: ['oil', 'cooking'],
    rating: 4.3,
    reviewCount: 44
  },
  {
    name: 'Pasta 500g',
    brand: 'Fatti\'s & Moni\'s',
    description: 'Spaghetti pasta',
    detailedDescription: 'Italian style pasta',
    price: 22.99,
    category: 'Groceries',
    subcategory: 'Grains',
    sku: 'GRO006',
    image: 'https://images.unsplash.com/photo-1551462147-37569e26d687?w=400',
    images: [],
    inStock: true,
    stockQuantity: 110,
    weight: '500g',
    manufacturer: 'Fatti\'s & Moni\'s',
    tags: ['pasta', 'italian'],
    rating: 4.4,
    reviewCount: 56
  },
  {
    name: 'Sugar 2.5kg',
    brand: 'Huletts',
    description: 'White sugar',
    detailedDescription: 'Pure white sugar',
    price: 38.99,
    category: 'Groceries',
    subcategory: 'Baking',
    sku: 'GRO007',
    image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=400',
    images: [],
    inStock: true,
    stockQuantity: 85,
    weight: '2.5kg',
    manufacturer: 'Huletts',
    tags: ['sugar', 'baking'],
    rating: 4.2,
    reviewCount: 33
  },
  {
    name: 'Coffee 200g',
    brand: 'Nescafe',
    description: 'Instant coffee',
    detailedDescription: 'Rich instant coffee',
    price: 89.99,
    category: 'Groceries',
    subcategory: 'Beverages',
    sku: 'GRO008',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=400',
    images: [],
    inStock: true,
    stockQuantity: 60,
    weight: '200g',
    manufacturer: 'Nescafe',
    tags: ['coffee', 'beverages'],
    rating: 4.7,
    reviewCount: 92
  },
  {
    name: 'Tomato Sauce 700ml',
    brand: 'All Gold',
    description: 'Tomato ketchup',
    detailedDescription: 'Classic tomato sauce',
    price: 28.99,
    category: 'Groceries',
    subcategory: 'Condiments',
    sku: 'GRO009',
    image: 'https://images.unsplash.com/photo-1567696153798-96ce7b7bd8f7?w=400',
    images: [],
    inStock: true,
    stockQuantity: 95,
    weight: '700ml',
    manufacturer: 'All Gold',
    tags: ['sauce', 'condiments'],
    rating: 4.5,
    reviewCount: 41
  },
  {
    name: 'Cereal 500g',
    brand: 'Kellogg\'s',
    description: 'Corn flakes',
    detailedDescription: 'Breakfast cereal',
    price: 52.99,
    category: 'Groceries',
    subcategory: 'Breakfast',
    sku: 'GRO010',
    image: 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cda9?w=400',
    images: [],
    inStock: true,
    stockQuantity: 75,
    weight: '500g',
    manufacturer: 'Kellogg\'s',
    tags: ['cereal', 'breakfast'],
    rating: 4.6,
    reviewCount: 58
  },

  // Transport Products (10)
  {
    name: 'Bus Monthly Pass - Student',
    brand: 'City Transport',
    description: 'Student monthly bus pass',
    detailedDescription: 'Unlimited travel for students',
    price: 150.00,
    category: 'Transport',
    subcategory: 'Public Transport',
    sku: 'TRP001',
    image: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=400',
    images: [],
    inStock: true,
    stockQuantity: 200,
    manufacturer: 'City Transport',
    tags: ['bus', 'student'],
    rating: 4.0,
    reviewCount: 8
  },
  {
    name: 'Taxi Voucher R100',
    brand: 'Uber',
    description: 'Uber taxi voucher',
    detailedDescription: 'R100 credit for Uber rides',
    price: 100.00,
    category: 'Transport',
    subcategory: 'Ride Services',
    sku: 'TRP002',
    image: 'https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=400',
    images: [],
    inStock: true,
    stockQuantity: 150,
    manufacturer: 'Uber',
    tags: ['taxi', 'uber'],
    rating: 4.5,
    reviewCount: 24
  },
  {
    name: 'Fuel Voucher R200',
    brand: 'Shell',
    description: 'Shell fuel voucher',
    detailedDescription: 'R200 fuel credit',
    price: 200.00,
    category: 'Transport',
    subcategory: 'Fuel',
    sku: 'TRP003',
    image: 'https://images.unsplash.com/photo-1545262810-77515befe149?w=400',
    images: [],
    inStock: true,
    stockQuantity: 100,
    manufacturer: 'Shell',
    tags: ['fuel', 'petrol'],
    rating: 4.6,
    reviewCount: 16
  },
  {
    name: 'Train Weekly Pass',
    brand: 'Metrorail',
    description: 'Weekly train pass',
    detailedDescription: 'Unlimited train travel for one week',
    price: 80.00,
    category: 'Transport',
    subcategory: 'Public Transport',
    sku: 'TRP004',
    image: 'https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400',
    images: [],
    inStock: true,
    stockQuantity: 180,
    manufacturer: 'Metrorail',
    tags: ['train', 'weekly'],
    rating: 3.9,
    reviewCount: 12
  },
  {
    name: 'Bicycle Lock',
    brand: 'Kryptonite',
    description: 'Heavy duty bike lock',
    detailedDescription: 'High security U-lock',
    price: 350.00,
    category: 'Transport',
    subcategory: 'Cycling',
    sku: 'TRP005',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    images: [],
    inStock: true,
    stockQuantity: 40,
    weight: '800g',
    manufacturer: 'Kryptonite',
    tags: ['bicycle', 'lock'],
    rating: 4.7,
    reviewCount: 31
  },
  {
    name: 'Helmet',
    brand: 'Bell',
    description: 'Safety bicycle helmet',
    detailedDescription: 'Adjustable safety helmet',
    price: 280.00,
    category: 'Transport',
    subcategory: 'Cycling',
    sku: 'TRP006',
    image: 'https://images.unsplash.com/photo-1558618047-a6f3c8563de3?w=400',
    images: [],
    inStock: true,
    stockQuantity: 35,
    weight: '300g',
    manufacturer: 'Bell',
    tags: ['helmet', 'safety'],
    rating: 4.5,
    reviewCount: 22
  },
  {
    name: 'Parking Voucher Monthly',
    brand: 'City Parking',
    description: 'Monthly parking pass',
    detailedDescription: 'Unlimited parking for one month',
    price: 450.00,
    category: 'Transport',
    subcategory: 'Parking',
    sku: 'TRP007',
    image: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=400',
    images: [],
    inStock: true,
    stockQuantity: 60,
    manufacturer: 'City Parking',
    tags: ['parking', 'monthly'],
    rating: 4.2,
    reviewCount: 9
  },
  {
    name: 'Reflective Vest',
    brand: 'SafetyFirst',
    description: 'High visibility vest',
    detailedDescription: 'Reflective safety vest',
    price: 65.00,
    category: 'Transport',
    subcategory: 'Safety',
    sku: 'TRP008',
    image: 'https://images.unsplash.com/photo-1614963366795-30e1e20dbb71?w=400',
    images: [],
    inStock: true,
    stockQuantity: 80,
    weight: '150g',
    manufacturer: 'SafetyFirst',
    tags: ['safety', 'reflective'],
    rating: 4.4,
    reviewCount: 18
  },
  {
    name: 'Toll Gate Tag',
    brand: 'E-Toll',
    description: 'Electronic toll tag',
    detailedDescription: 'Prepaid toll gate tag',
    price: 120.00,
    category: 'Transport',
    subcategory: 'Toll',
    sku: 'TRP009',
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400',
    images: [],
    inStock: true,
    stockQuantity: 70,
    weight: '50g',
    manufacturer: 'E-Toll',
    tags: ['toll', 'electronic'],
    rating: 4.3,
    reviewCount: 14
  },
  {
    name: 'Car Air Freshener Pack',
    brand: 'Little Trees',
    description: 'Car air fresheners',
    detailedDescription: 'Pack of 5 assorted scents',
    price: 45.00,
    category: 'Transport',
    subcategory: 'Car Accessories',
    sku: 'TRP010',
    image: 'https://images.unsplash.com/photo-1610647752706-3bb12232b3ab?w=400',
    images: [],
    inStock: true,
    stockQuantity: 120,
    weight: '100g',
    manufacturer: 'Little Trees',
    tags: ['car', 'freshener'],
    rating: 4.1,
    reviewCount: 27
  },

  // Entertainment Products (10)
  {
    name: 'Movie Tickets 2-Pack',
    brand: 'Ster Kinekor',
    description: 'Two cinema tickets',
    detailedDescription: 'Valid for any standard screening',
    price: 220.00,
    category: 'Entertainment',
    subcategory: 'Cinema',
    sku: 'ENT001',
    image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    images: [],
    inStock: true,
    stockQuantity: 75,
    manufacturer: 'Ster Kinekor',
    tags: ['movies', 'cinema'],
    rating: 4.6,
    reviewCount: 32
  },
  {
    name: 'Board Game - Monopoly',
    brand: 'Hasbro',
    description: 'Classic Monopoly game',
    detailedDescription: 'Family board game',
    price: 450.00,
    category: 'Entertainment',
    subcategory: 'Games',
    sku: 'ENT002',
    image: 'https://images.unsplash.com/photo-1611891487281-f5d7c1b9b34a?w=400',
    images: [],
    inStock: true,
    stockQuantity: 30,
    weight: '800g',
    manufacturer: 'Hasbro',
    tags: ['board game', 'family'],
    rating: 4.7,
    reviewCount: 48
  },
  {
    name: 'PlayStation Gift Card R500',
    brand: 'Sony',
    description: 'PSN gift card',
    detailedDescription: 'R500 PlayStation Store credit',
    price: 500.00,
    category: 'Entertainment',
    subcategory: 'Gaming',
    sku: 'ENT003',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400',
    images: [],
    inStock: true,
    stockQuantity: 100,
    manufacturer: 'Sony',
    tags: ['playstation', 'gaming'],
    rating: 4.8,
    reviewCount: 65
  },
  {
    name: 'Puzzle 1000 Pieces',
    brand: 'Ravensburger',
    description: 'Jigsaw puzzle',
    detailedDescription: '1000 piece landscape puzzle',
    price: 280.00,
    category: 'Entertainment',
    subcategory: 'Puzzles',
    sku: 'ENT004',
    image: 'https://images.unsplash.com/photo-1609775782748-7ac3f0f72696?w=400',
    images: [],
    inStock: true,
    stockQuantity: 40,
    weight: '600g',
    manufacturer: 'Ravensburger',
    tags: ['puzzle', 'jigsaw'],
    rating: 4.5,
    reviewCount: 29
  },
  {
    name: 'Netflix Gift Card R200',
    brand: 'Netflix',
    description: 'Netflix subscription card',
    detailedDescription: 'R200 Netflix credit',
    price: 200.00,
    category: 'Entertainment',
    subcategory: 'Streaming',
    sku: 'ENT005',
    image: 'https://images.unsplash.com/photo-1574375927938-d5a98e8ffe85?w=400',
    images: [],
    inStock: true,
    stockQuantity: 150,
    manufacturer: 'Netflix',
    tags: ['netflix', 'streaming'],
    rating: 4.9,
    reviewCount: 87
  },
  {
    name: 'Soccer Ball',
    brand: 'Adidas',
    description: 'Professional soccer ball',
    detailedDescription: 'Size 5 match ball',
    price: 380.00,
    category: 'Entertainment',
    subcategory: 'Sports',
    sku: 'ENT006',
    image: 'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0aab?w=400',
    images: [],
    inStock: true,
    stockQuantity: 45,
    weight: '450g',
    manufacturer: 'Adidas',
    tags: ['soccer', 'sports'],
    rating: 4.6,
    reviewCount: 38
  },
  {
    name: 'Coloring Book Set',
    brand: 'Crayola',
    description: 'Adult coloring books',
    detailedDescription: 'Pack of 3 coloring books',
    price: 150.00,
    category: 'Entertainment',
    subcategory: 'Arts & Crafts',
    sku: 'ENT007',
    image: 'https://images.unsplash.com/photo-1612828022975-6e141f87fd67?w=400',
    images: [],
    inStock: true,
    stockQuantity: 55,
    weight: '400g',
    manufacturer: 'Crayola',
    tags: ['coloring', 'arts'],
    rating: 4.4,
    reviewCount: 26
  },
  {
    name: 'Card Game - UNO',
    brand: 'Mattel',
    description: 'Classic UNO card game',
    detailedDescription: 'Family card game',
    price: 120.00,
    category: 'Entertainment',
    subcategory: 'Games',
    sku: 'ENT008',
    image: 'https://images.unsplash.com/photo-1566694271453-390536dd1f0d?w=400',
    images: [],
    inStock: true,
    stockQuantity: 80,
    weight: '200g',
    manufacturer: 'Mattel',
    tags: ['card game', 'family'],
    rating: 4.7,
    reviewCount: 54
  },
  {
    name: 'Bluetooth Speaker',
    brand: 'JBL',
    description: 'Portable speaker',
    detailedDescription: 'Waterproof bluetooth speaker',
    price: 850.00,
    category: 'Entertainment',
    subcategory: 'Audio',
    sku: 'ENT009',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400',
    images: [],
    inStock: true,
    stockQuantity: 25,
    weight: '500g',
    manufacturer: 'JBL',
    tags: ['speaker', 'bluetooth'],
    rating: 4.8,
    reviewCount: 72
  },
  {
    name: 'Comic Book Collection',
    brand: 'Marvel',
    description: 'Marvel comic bundle',
    detailedDescription: 'Pack of 5 Marvel comics',
    price: 320.00,
    category: 'Entertainment',
    subcategory: 'Books',
    sku: 'ENT010',
    image: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?w=400',
    images: [],
    inStock: true,
    stockQuantity: 35,
    weight: '300g',
    manufacturer: 'Marvel',
    tags: ['comics', 'marvel'],
    rating: 4.5,
    reviewCount: 41
  },

  // Other Products (10)
  {
    name: 'Phone Charger USB-C',
    brand: 'Samsung',
    description: 'Fast charging cable',
    detailedDescription: 'USB-C charging cable 2m',
    price: 180.00,
    category: 'Other',
    subcategory: 'Electronics',
    sku: 'OTH001',
    image: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=400',
    images: [],
    inStock: true,
    stockQuantity: 90,
    weight: '100g',
    manufacturer: 'Samsung',
    tags: ['charger', 'electronics'],
    rating: 4.4,
    reviewCount: 34
  },
  {
    name: 'Water Bottle 1L',
    brand: 'Tupperware',
    description: 'Reusable water bottle',
    detailedDescription: 'BPA-free plastic bottle',
    price: 95.00,
    category: 'Other',
    subcategory: 'Household',
    sku: 'OTH002',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400',
    images: [],
    inStock: true,
    stockQuantity: 120,
    weight: '150g',
    manufacturer: 'Tupperware',
    tags: ['bottle', 'hydration'],
    rating: 4.5,
    reviewCount: 47
  },
  {
    name: 'Umbrella',
    brand: 'Totes',
    description: 'Compact folding umbrella',
    detailedDescription: 'Windproof automatic umbrella',
    price: 220.00,
    category: 'Other',
    subcategory: 'Accessories',
    sku: 'OTH003',
    image: 'https://images.unsplash.com/photo-1590628073837-4ab16e86b560?w=400',
    images: [],
    inStock: true,
    stockQuantity: 60,
    weight: '400g',
    manufacturer: 'Totes',
    tags: ['umbrella', 'rain'],
    rating: 4.3,
    reviewCount: 23
  },
  {
    name: 'Sunglasses',
    brand: 'Ray-Ban',
    description: 'UV protection sunglasses',
    detailedDescription: 'Polarized lens sunglasses',
    price: 850.00,
    category: 'Other',
    subcategory: 'Fashion',
    sku: 'OTH004',
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400',
    images: [],
    inStock: true,
    stockQuantity: 35,
    weight: '100g',
    manufacturer: 'Ray-Ban',
    tags: ['sunglasses', 'fashion'],
    rating: 4.8,
    reviewCount: 56
  },
  {
    name: 'Watch Digital',
    brand: 'Casio',
    description: 'Digital wristwatch',
    detailedDescription: 'Water resistant digital watch',
    price: 450.00,
    category: 'Other',
    subcategory: 'Accessories',
    sku: 'OTH005',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
    images: [],
    inStock: true,
    stockQuantity: 45,
    weight: '80g',
    manufacturer: 'Casio',
    tags: ['watch', 'digital'],
    rating: 4.6,
    reviewCount: 38
  },
  {
    name: 'Torch LED',
    brand: 'Energizer',
    description: 'LED flashlight',
    detailedDescription: 'Rechargeable LED torch',
    price: 320.00,
    category: 'Other',
    subcategory: 'Tools',
    sku: 'OTH006',
    image: 'https://images.unsplash.com/photo-1609077385168-e5d9f166a6d7?w=400',
    images: [],
    inStock: true,
    stockQuantity: 55,
    weight: '250g',
    manufacturer: 'Energizer',
    tags: ['torch', 'led'],
    rating: 4.5,
    reviewCount: 29
  },
  {
    name: 'Batteries AA Pack (8)',
    brand: 'Duracell',
    description: 'Alkaline batteries',
    detailedDescription: 'Long-lasting AA batteries',
    price: 85.00,
    category: 'Other',
    subcategory: 'Electronics',
    sku: 'OTH007',
    image: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=400',
    images: [],
    inStock: true,
    stockQuantity: 150,
    weight: '200g',
    manufacturer: 'Duracell',
    tags: ['batteries', 'power'],
    rating: 4.7,
    reviewCount: 64
  },
  {
    name: 'Blanket Fleece',
    brand: 'Mr Price Home',
    description: 'Soft fleece blanket',
    detailedDescription: 'King size fleece blanket',
    price: 380.00,
    category: 'Other',
    subcategory: 'Household',
    sku: 'OTH008',
    image: 'https://images.unsplash.com/photo-1631637870630-bd7de9808d23?w=400',
    images: [],
    inStock: true,
    stockQuantity: 40,
    weight: '1.2kg',
    manufacturer: 'Mr Price Home',
    tags: ['blanket', 'bedding'],
    rating: 4.4,
    reviewCount: 31
  },
  {
    name: 'Cleaning Supplies Kit',
    brand: 'Handy Andy',
    description: 'Complete cleaning set',
    detailedDescription: 'Includes cleaner, sponges, cloths',
    price: 150.00,
    category: 'Other',
    subcategory: 'Household',
    sku: 'OTH009',
    image: 'https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400',
    images: [],
    inStock: true,
    stockQuantity: 70,
    weight: '1kg',
    manufacturer: 'Handy Andy',
    tags: ['cleaning', 'household'],
    rating: 4.2,
    reviewCount: 25
  },
  {
    name: 'Gift Card R500',
    brand: 'Takealot',
    description: 'Takealot voucher',
    detailedDescription: 'R500 shopping voucher',
    price: 500.00,
    category: 'Other',
    subcategory: 'Vouchers',
    sku: 'OTH010',
    image: 'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?w=400',
    images: [],
    inStock: true,
    stockQuantity: 200,
    manufacturer: 'Takealot',
    tags: ['voucher', 'gift card'],
    rating: 4.9,
    reviewCount: 92
  }
];

const seedProducts = async () => {
  try {
    console.log('🌱 Starting product seeding...');
    
    // Clear existing products (optional - without truncate to avoid foreign key issues)
    await Product.destroy({ where: {} });
    console.log('🗑️ Cleared existing products');
    
    // Insert sample products
    const createdProducts = await Product.bulkCreate(sampleProducts, {
      returning: true
    });
    
    console.log(`✅ Successfully seeded ${createdProducts.length} products:`);
    
    createdProducts.forEach(product => {
      console.log(`   - ${product.name} (${product.category}) - R${product.price}`);
    });
    
    console.log('🎉 Product seeding completed!');
    
  } catch (error) {
    console.error('❌ Product seeding failed:', error);
    throw error;
  }
};

// Run seeding if this file is executed directly
if (require.main === module) {
  const { sequelize } = require('../models');
  
  sequelize.authenticate()
    .then(seedProducts)
    .then(() => {
      console.log('✨ Database seeding completed successfully!');
      process.exit(0);
    })
    .catch(error => {
      console.error('💥 Database seeding failed:', error);
      process.exit(1);
    });
}

module.exports = { seedProducts, sampleProducts };
